//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.AchievementsService"/> </summary
    public sealed class AchievementsServiceClient : MicroserviceClient
    {
        
        public AchievementsServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        /// <summary>
        /// Call the LoadAchievements method on the AchievementsService microservice
        /// <see cref="Beamable.Microservices.AchievementsService.LoadAchievements"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.List<Beamable.Microservices.AchievementContent>> LoadAchievements()
        {
            string[] serializedFields = new string[0];
            return this.Request<System.Collections.Generic.List<Beamable.Microservices.AchievementContent>>("AchievementsService", "LoadAchievements", serializedFields);
        }
        
        /// <summary>
        /// Call the CheckAchievements method on the AchievementsService microservice
        /// <see cref="Beamable.Microservices.AchievementsService.CheckAchievements"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.Dictionary<string, bool>> CheckAchievements()
        {
            string[] serializedFields = new string[0];
            return this.Request<System.Collections.Generic.Dictionary<string, bool>>("AchievementsService", "CheckAchievements", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersAchievementsServiceClient
    {
    }
    
    [BeamContextSystemAttribute()]
    internal static class ExtensionsForAchievementsServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<AchievementsServiceClient>();
        }
        
        public static AchievementsServiceClient AchievementsService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<AchievementsServiceClient>();
        }
    }
}
