//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.ProcessPostGameResults"/> </summary
    public sealed class ProcessPostGameResultsClient : MicroserviceClient
    {
        
        public ProcessPostGameResultsClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        /// <summary>
        /// Call the ProcessResults method on the ProcessPostGameResults microservice
        /// <see cref="Beamable.Microservices.ProcessPostGameResults.ProcessResults"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Microservices.PostGameResult> ProcessResults(int score, int finishPosition, int totalKills)
        {
            string serialized_score = this.SerializeArgument<int>(score);
            string serialized_finishPosition = this.SerializeArgument<int>(finishPosition);
            string serialized_totalKills = this.SerializeArgument<int>(totalKills);
            string[] serializedFields = new string[] {
                    serialized_score,
                    serialized_finishPosition,
                    serialized_totalKills};
            return this.Request<Beamable.Microservices.PostGameResult>("ProcessPostGameResults", "ProcessResults", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersProcessPostGameResultsClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    internal static class ExtensionsForProcessPostGameResultsClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<ProcessPostGameResultsClient>();
        }
        
        public static ProcessPostGameResultsClient ProcessPostGameResults(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<ProcessPostGameResultsClient>();
        }
    }
}
